import Head from 'next/head'
import Image from 'next/image'
import { Header } from '../components/header'
import styles from '../../styles/Home.module.css'

import Avatar from '../assets/img/avatar.svg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Leonardo Rezende | Portifólio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* Header */}
        <Header></Header>

        {/* CAPA */}
        <section>
          <div className="container">
            <div className="row">
              <div className="row text-center padding-top-8">
                <h1 className="text-white fs-2">Oi, eu sou o <span className="text-destaque">Leonardo</span> 👋</h1>
                <h2 className="text-white fs-0 mt-3">Aspirante em Desenvolvimento Web</h2>
                <p className="text-white fs-4 fw-light mt-5">Atualmente sou um iniciante na área, que adora o que está descobrindo!</p>
              </div>

              <div className="row justify-content-center">
                <Image src={Avatar} width={210} height={220}/>
                </div>
            </div>

          </div>
        </section>


      </main>

    </>
  )
}
